//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkHelper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndicationParBoutique
    {
        public int Id { get; set; }
        public int IdIndication { get; set; }
        public int IdBoutique { get; set; }
    
        public virtual Boutique Boutique { get; set; }
        public virtual Indication Indication { get; set; }
    }
}
