//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkHelper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lieu()
        {
            this.Indications = new HashSet<Indication>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string LienGif { get; set; }
        public Nullable<double> Latittude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<int> Attente { get; set; }
        public Nullable<int> Duree { get; set; }
        public Nullable<int> CapaciteWagon { get; set; }
        public Nullable<int> IdType { get; set; }
        public Nullable<int> Ordre { get; set; }
        public bool EstDejaDansLeParcours { get; set; }
        public virtual TypeDeLieu TypeDeLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indication> Indications { get; set; }
    }
}
