//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace ParkHelper.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lieu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lieu()
        {
            this.Indications = new HashSet<Indication>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Description { get; set; }
        public string LienGif { get; set; }
        public double? Latittude { get; set; }
        public double? Longitude { get; set; }
        public int? Attente { get; set; }
        public int? Duree { get; set; }
        public int Ordre { get; set; }
        public bool EstDejaDansLeParcours { get; set; }
        public int? CapaciteWagon { get; set; }
        public int? IdType { get; set; }
        public int? IdEtat { get; set; }
        [ForeignKey("IdType")]
        public virtual TypeDeLieu TypeDeLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indication> Indications { get; set; }
        [ForeignKey("IdEtat")]
        public virtual EtatLieu EtatLieu { get; set; }
    }
}
