//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkHelper.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParcHelperEntities : DbContext
    {
        public ParcHelperEntities()
            : base("name=ParcHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EtatLieu> EtatLieux { get; set; }
        public virtual DbSet<Horaire> Horaires { get; set; }
        public virtual DbSet<Indication> Indications { get; set; }
        public virtual DbSet<Jour> Jours { get; set; }
        public virtual DbSet<Lieu> Lieux { get; set; }
        public virtual DbSet<TypeDeLieu> TypeDeLieux { get; set; }
        public virtual DbSet<Date> Dates { get; set; }
        public virtual DbSet<Mois> Mois { get; set; }
        public virtual DbSet<Planning> Plannings { get; set; }
    }
}
